### ISSUE TITLE
Use case document

### ISSUE THREAD

**Issue by mturilli** [jonatanYanovsky/dashboard#1]

**Comment by mturilli** [comment]
Ping. Are you writing this document?

**Comment by jonatanYanovsky** [comment]
yes, we will start it tomorrow.

**Comment by jonatanYanovsky** [comment]
Use cases are coming to a halt as we do not understand how this project will help scientists solve problems with their HPC environment.

We are going with just a single PST visualization showing the duration of pipelines/states/tasks and the events that occur during their execution.
