### ISSUE TITLE
PST Model Documentation

### ISSUE THREAD

**Issue by rahulgupta-mmr** [jonatanYanovsky/dashboard#10]
With respect to examples with multiple pipelines, we would like to better understand the semantics of the execution based on the Pipeline/Stage/Task model. 

```
sync_abs
tmgr process started
tmgr infrastructure setup done
transition
publishing obj with state SUBMITTING for sync
obj with state SUBMITTING synchronized
cud from task - create
cud from task - done
transition
publishing obj with state SUBMITTED for sync
obj with state SUBMITTED synchronized
task from cu - create
task from cu - done
transition
publishing obj with state EXECUTED for sync
obj with state EXECUTED synchronized
transition
terminating tmgr process
END
```

We have isolated the above states in an order we saw multiple times while analyzing the task flow. However, we are not sure if this is the correct transitioning. As we are currently creating a visualization showing the relationship between (1) stages and tasks, per one pipeline, and then (2) stages and tasks, per all pipelines present, we want to understand where the pipelining is occurring. 

Is there a link to any documentation covering this material? We have already referred to radicalensemble documentation (readthedocs) and found only a visualization for the PST model itself, but need advice pertaining specifically to the data in each example.

**Comment by mturilli** [comment]
States: https://radicalentk.readthedocs.io/en/latest/dev_docs/uml.html#dev-docs-state-model
Events: https://radicalentk.readthedocs.io/en/latest/dev_docs/uml.html#dev-docs-events
Profiler: https://radicalentk.readthedocs.io/en/latest/user_guide/profiling.html
EnTK: https://radicalentk.readthedocs.io/en/latest/index.html
