### ISSUE TITLE
Why does config file have a break in the middle?

### ISSUE THREAD

**Issue by jonatanYanovsky** [jonatanYanovsky/dashboard#11]
In "radical.entk.task_manager.0000-proc.prof' which we have in the github,
it goes like this twice:

at the top
#time,event,comp,thread,uid,state,msg
1518814386.9899,sync_abs,radical.entk.task_manager.0000-proc,MainThread,,,jon-VirtualBox:127.0.0.1:1518814386.98:1518814386.98:sys

in the middle
#time,event,comp,thread,uid,state,msg
1518814784.7066,sync_abs,radical.entk.task_manager.0000-proc,MainThread,,,jon-VirtualBox:127.0.0.1:1518814784.71:1518814784.71:sys

Is this a result of running the example twice?
Should we remove the second?
Or is this an example of two pipelines?

**Comment by andre-merzky** [comment]
Those are the profiles.  The headers are written when a profile is opened.  If the same profile is opened by different processes or threads or classes or whatever, the header is written twice.  Your parser should ignore the `#` header lines.  The `sync_abs` lines are redundant, but otherwise valid.

**Comment by jonatanYanovsky** [comment]
In other words, do we need to parse both profiles? Or only the first one?

Furthermore, we only ran a single example to get those results. If we run the examples twice, will the second execution overwrite or simply append its output to the log file?

**Comment by andre-merzky** [comment]
What profiles you need to parse depends on what events you want to obtain - different profiles typically contain different event types.

RP profiles are not overwritten - they are stored in a subdir with the session ID.  I can't speak for the EnTK profiles - @vivek-bala ?

**Comment by mturilli** [comment]
> Furthermore, we only ran a single example to get those results. If we run the examples twice, will the second execution overwrite or simply append its output to the log file?

Did you try?

**Comment by vivek-bala** [comment]
Depending on the version, yes and no. If you tried the latest release (0.6.0), EnTK profiles should also be generated in a separate folder (where the folder name starts as re.session.<id>). If you were using the older version (or earlier devel), yes your observation is correct the profiles will get overwritten. My suggestion would be to upgrade to the latest release.

**Comment by mturilli** [comment]
I echo @vivek-bala suggestion: upgrade to the latest version of EnTK that was released last week. See https://packaging.python.org/tutorials/installing-packages/#upgrading-packages for using `pip` to upgrade a package you have already installed. **Activate** your virtual environment before using `pip`.

**Comment by jonatanYanovsky** [comment]
I will try this

**Comment by jonatanYanovsky** [comment]
I tried the update, there is still a break in the middle of the log where it goes:
`#time,event,comp,thread,uid,state,msg`

**Comment by andre-merzky** [comment]
This will always be the case.  Your compiler should ignore lines starting with `#`, ie. intermittent header lines.

**Comment by jonatanYanovsky** [comment]
I am looking at the `radical.entk.appmanager.0000.prof` file in the `radical.entk/examples/simple-examples/` folder. However, it looks like it never changes. Perhaps I have been parsing the wrong file all along.
Nvm. There is another folder by the name of `radical.entk/examples/simple-examples/re.session.jon-VirtualBox.jon.017600.0000` which contains the same file without the break.
