### ISSUE TITLE
Why are the tasks and stages numbered the same?

### ISSUE THREAD

**Issue by jonatanYanovsky** [jonatanYanovsky/dashboard#12]
1518814847.5735,publishing obj with state EXECUTED for sync,radical.entk.task_manager.0000-proc,umgr.0000.subscriber._state_sub_cb,**radical.entk.task.0023**,,**radical.entk.stage.0023**

1518814848.2923,obj with state EXECUTED synchronized,radical.entk.task_manager.0000-proc,umgr.0000.subscriber._state_sub_cb,**radical.entk.task.0020**,,**radical.entk.stage.0020**

**Comment by andre-merzky** [comment]
Well, they are different things, so they have their own numbering.  This is like asking why, on February second, month and day have the same number - why not? :-)

**Comment by jonatanYanovsky** [comment]
Is it a coincidence that they are all the same? Or is it that the system is programmed to put the same numbers on the same lines - that the states go with their respectively numbered tasks?

**Comment by andre-merzky** [comment]
The relation between pipeline and task IDs depends on the specific workload - I think you can consider the actual numbers as coincidental - they are really just unique names, and could be random strings for all practical purposes.

**Comment by vivek-bala** [comment]
The UID of the stage is "radical.entk.stage.0020" and "radical.entk.task.0020" is the UID of task. You should consider the entire string and not just the numbers to look for uniqueness in the ID between objects.
