### ISSUE TITLE
Which output folder contains the appmanager log file?

### ISSUE THREAD

**Issue by jonatanYanovsky** [jonatanYanovsky/dashboard#13]
running examples creates two directories in the same folder as the example.
 one will be named `re.session.jon-VirtualBox.jon.[num1].[odd or even number]` and the other `rp.session.jon-VirtualBox.jon.[num1].[even or odd number]`

Only one contains the `radical.entk.appmanager.0000.prof` but the location of this file is not consistent between different examples. In the simple_examples, the appmanager would be in `re.*`, but in examples, it is in the `rp.*`

**Comment by andre-merzky** [comment]
This is something @vivek-bala should be able to help with.  I assume you trigger some inconsistency in the naming of the session, which is likely a leftover from a renaming effort.

**Comment by jonatanYanovsky** [comment]
Actually I think I got this wrong. It appears that only the `re.*` folders contain the needed data
