### ISSUE TITLE
Problem running exmple

### ISSUE THREAD

**Issue by jonatanYanovsky** [jonatanYanovsky/dashboard#2]
jon@jon-VirtualBox:~/radical.entk/examples$ python example1.py 
Traceback (most recent call last):
  File "example1.py", line 1, in <module>
    from radical.entk import Pipeline, Stage, Task, AppManager, ResourceManager
ImportError: No module named radical.entk

**Comment by mturilli** [comment]
From Andre: "This seems to indicate a problem with the virtualenv setup. Can you please link the exact tutorial page you have been following? Thanks."

**Comment by jonatanYanovsky** [comment]
This guide: http://radicalensemblemd.readthedocs.io/en/devel/install.html
We skipped part 3.4 and then tried to run the examples

**Comment by mturilli** [comment]
From Vivek:

Hey, you need to use the following documentation: http://radicalensemblemd.readthedocs.io/en/devel/index.html (I think you might be using an older version). You can run any of the examples in the above link.

The installation instructions would be as follows (from a terminal of your Ubuntu installation):
```
virtualenv $HOME/myenv
source $HOME/myenv/bin/activate
cd $HOME
pip install radical.pilot
git clone https://github.com/radical-cybertools/radical.entk.git
cd radical.entk
git checkout devel
pip install .
export RADICAL_PILOT_DBURL="mongodb://138.201.86.166:27017/ee_exp_4c"
export RADICAL_PILOT_PROFILE=True
export RADICAL_ENTK_PROFILE=True
export RP_ENABLE_OLD_DEFINES=True
```

You need to set two environment variables to get the execution profiles: ```export RADICAL_PILOT_PROFILE=True``` and ```export RADICAL_ENTK_PROFILE=True```

Note: You have to configure ssh to access localhost (assuming you are running your example on localhost) **without** password. Please follow these instructions:

```
ssh-keygen -t rsa
cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
```

**Comment by jonatanYanovsky** [comment]
I did that, then I wen't here: http://radicalensemblemd.readthedocs.io/en/devel/examples/poe.html

I ran an example (after setting the environment variables) and got the following error:

jon@jon-VirtualBox:~/radical.entk/examples/simple_examples$ python poe.py 
Traceback (most recent call last):
  File "poe.py", line 1, in <module>
    from radical.entk import Pipeline, Stage, Task, AppManager, ResourceManager
ImportError: No module named radical.entk

**Comment by mturilli** [comment]
I do not see your virtual env activated in: `jon@jon-VirtualBox:~/radical.entk/examples/simple_examples$ python poe.py`

Are you attempting to run the example from the *same* shell from which you executed the commands suggested by Vivek?

**Comment by jonatanYanovsky** [comment]
yes

**Comment by mturilli** [comment]
Please go to http://persistenthangout.tk from a chrome browser on the same machine on which you are trying to run the example. This will require audio and microphone.
