### ISSUE TITLE
Failing to run examples

### ISSUE THREAD

**Issue by rahulgupta-mmr** [jonatanYanovsky/dashboard#4]
Hi All,

I've been having an issue running the examples in EnTK. When running examples such as poe.py and eop.py, I am receiving errors as can be seen by the state transitions. I have also gotten an error saying gsissh not found. Please advise. 

![virtualbox_radicalproject_17_02_2018_14_47_29](https://user-images.githubusercontent.com/20449071/36345074-7230d498-13f2-11e8-8a90-5da475fa3ba5.png)
![virtualbox_radicalproject_17_02_2018_14_46_40](https://user-images.githubusercontent.com/20449071/36345075-725d5ce8-13f2-11e8-8aa6-8100b2b2b0ad.png)

**Comment by rahulgupta-mmr** [comment]
Sorry, screenshot came out blank. Here is the screenshot: 

![capture](https://user-images.githubusercontent.com/20449071/36345130-53d468a6-13f3-11e8-8995-31e286516485.PNG)

**Comment by mturilli** [comment]
Hi Rahul,

Did you configure passwordless ssh access to localhost as discussed at our last meeting?
